"""project table

Revision ID: 9b8fcc22b4e1
Revises: 
Create Date: 2020-08-08 22:25:13.934036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8fcc22b4e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True, is_unique=True),
    sa.Column('project_name', sa.String(length=4986), nullable=True),
    sa.Column('github_link', sa.String(length=12096), nullable=True),
    sa.Column('author', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
